# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 921346fb35f34de13d85b195c0df69e1562344104a438b483032d496c6d67e8f48c83139a33ba298a7c42dd4ce57913f80b800f71d9d280e4d3b9c2574eed29b

test:
  secret_key_base: 70bf0242e3d7b872ba982686ecf9cae0de567d9d9d81bf6a4d2fbe8467d1ce3e610cb53b05ff38906916b9ce362ff44844dddbec50f06732cddae7f98e850070

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
